"""fixes to fields

Revision ID: 3a1ed01222eb
Revises: 1bb03eb286c9
Create Date: 2025-02-27 13:04:28.046238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a1ed01222eb'
down_revision: Union[str, None] = '1bb03eb286c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attacks', sa.Column('attack_bonus', sa.Integer(), nullable=True))
    op.drop_column('attacks', 'bonus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attacks', sa.Column('bonus', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('attacks', 'attack_bonus')
    # ### end Alembic commands ###
