"""fixed cascade delete

Revision ID: 910887d0165a
Revises: 6d7cf04a889f
Create Date: 2025-02-26 17:10:03.640437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '910887d0165a'
down_revision: Union[str, None] = '6d7cf04a889f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('traits', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('traits', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('traits', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('traits', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
