"""fixes to fields

Revision ID: 1bb03eb286c9
Revises: 910887d0165a
Create Date: 2025-02-27 13:01:12.388564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bb03eb286c9'
down_revision: Union[str, None] = '910887d0165a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attacks', 'type')
    op.add_column('equipment', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'description')
    op.add_column('attacks', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
