"""fixed proficiency bonus field name

Revision ID: 6d7cf04a889f
Revises: c9dda1d04bcd
Create Date: 2025-02-26 14:35:22.987002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d7cf04a889f'
down_revision: Union[str, None] = 'c9dda1d04bcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('proficiency_bonus', sa.Integer(), nullable=True))
    op.drop_column('characters', 'proficency_bonus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('proficency_bonus', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('characters', 'proficiency_bonus')
    # ### end Alembic commands ###
