"""fixes to fields

Revision ID: 7b3fdc454d3f
Revises: 3a1ed01222eb
Create Date: 2025-02-27 13:06:21.283880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b3fdc454d3f'
down_revision: Union[str, None] = '3a1ed01222eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('description', sa.String(), nullable=True))
    op.add_column('proficiencies', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('traits', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('traits', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('proficiencies', 'description')
    op.drop_column('languages', 'description')
    # ### end Alembic commands ###
